### ISSUE TITLE
Add resource to collection without saving

### ISSUE THREAD

**Issue by dustinblanchard** [reyesoft/ngx-jsonapi#110]
I am trying to use this along with webhooks in my application. For instance, when I have a new notification, my Angular application receives the JSON of the new notification. I need to be able to do two things:

- I need to make sure this resource does not already exist in the collection. 
- If it does not already exist in the collection, I need a way to add it to the collection without saving it to the API (since it came from the server in the first place).

Is there a way to extend .new() to allow me to 
1. create the resource using the JSON from my webhook.
2. verify no duplicate resource already exists in the collection (match id or the full object)
3. add the resource to the collection (updating the observable in my controller)

**Comment by pablorsk** [comment]
V2.0

> I need to make sure this resource does not already exist in the collection.  If it does not already exist in the collection, I need a way to add it to the collection without saving it to the API (since it came from the server in the first place).
```typescript
colleciton.replaceOrAdd(resource); // resource is Resource type
```

> create the resource using the JSON from my webhook.
```typescript
resource = service.new();
resource.fill(data);
```
