### ISSUE TITLE
Issue saving the resource

### ISSUE THREAD

**Issue by NazarioLeonPerez** [reyesoft/ngx-jsonapi#115]
Testing the code:
```typescript    
    let user = this.usersService.new();
    user.attributes.userName = this.f.username.value;
    user.attributes.password = this.f.password.value;
    user.save();
```
i realized that it does not do anything because the save method in the class Resource does this control
```typescript
        if (this.is_saving || this.is_loading) {
            return of({});
        }
```    
and is_loading property is initialized to true.
The demo does not work either.

**Comment by pablorsk** [comment]
Your are right. Problem solved and published on `2.0.0-rc.5`
