### ISSUE TITLE
Should remotefilter be encoding [ ]?

### ISSUE THREAD

**Issue by peavers** [reyesoft/ngx-jsonapi#118]
I've noticed when using `remotefilter` it's sending the a request that looks like `http://localhost:8082/steaks?filter[color]=blue` which blows up my (and probably most peoples) backend services as `[]` are not allowed characters. 

Should it be encoded first, or am I supposed to do that myself?

**Comment by pablorsk** [comment]
Hi @peavers, "arrays" on GET params are valid with apache and the most web servers.  If you encode that, you can not read correcty on PHP servers, for example.

Please check specification example: http://jsonapi.org/examples/#pagination and ([RFC 1738](http://www.ietf.org/rfc/rfc1738.txt)). 

URLs with brackets are valid. If you need more information, please share your backend type.
