### ISSUE TITLE
Pagination zero indexed support

### ISSUE THREAD

**Issue by NazarioLeonPerez** [reyesoft/ngx-jsonapi#120]
Hi, i've noticed when using the integrated pagination feature that it does not support zero as start index which although it is not common practice is a possibility that should be considered. 
I found che in the "PathCollectionBuilder" class the following control
`
if (params.page.number > 1) {
                this.addParam(Core.injectedServices.rsJsonapiConfig.parameters.page.number + '=' + params.page.number);
            }
`
cause that the page param with 0 and 1 index will not be included.

**Comment by pablorsk** [comment]
This is for web browser cache reasons...

For example these URLs return same information:
* http://jsonapiplayground.reyesoft.com/v2/books
* http://jsonapiplayground.reyesoft.com/v2/books?page[number]=1
* http://jsonapiplayground.reyesoft.com/v2/books?page[number]=01
* http://jsonapiplayground.reyesoft.com/v2/books?page[number]=001

But web browser make every request :/
