### ISSUE TITLE
How to disable all caching? 

### ISSUE THREAD

**Issue by peavers** [reyesoft/ngx-jsonapi#130]
The caching mechanism seems pretty buggy around relationships and removal/add operations. I'd like to fully disable any caching but I don't see a flag for it?

**Comment by iamchrismiller** [comment]
There is a configuration object that you can configure in the root of your application.

`JsonapiConfig` (https://github.com/reyesoft/ngx-jsonapi/blob/cd063ec3058898a0604c268f3188694495c0122a/src/jsonapi-config.ts)

We removed all caching with the following configuration:

```
    NgxJsonapiModule.forRoot({
      url: '/',
      cache_prerequests: false,
      cachestore_support: false
    })
```

**Comment by xaun** [comment]
@iamchrismiller objects are still set to cachememory with this disabled, and on versions 1.1.0, cachememory is really buggy - not sure if this has been fixed on later versions, but I don't really want to invest any more time on this library to confirm / investigate.

**Comment by wojo1206** [comment]
Cache in `^2.0.0-rc.4` can be successfully disabled.
