### ISSUE TITLE
Empty relationship data when updating resource with optional relationship.

### ISSUE THREAD

**Issue by Maan511** [reyesoft/ngx-jsonapi#132]
When saving a resource with an optional to-one relationship which has not been set, a relationship object with an empty data attribute is sent to the server, along with other updates.
```
{
  "data": {
    // "id", "type" and "attributes" left out
    "relationships": {
      "Part": { "data": { } }
    }
  }
}
```

If I understand the [documentation](https://jsonapi.org/format/#crud-updating-relationships) correctly, this is not valid.
> The PATCH request MUST include a top-level member named data containing one of:
> - a resource identifier object corresponding to the new related resource.
> - null, to remove the relationship.

In my case where the relationship is not set to a resource, I would expect the `Part` relationship object to be left out of the update request,

**Comment by pablorsk** [comment]
Can you build a small example? you are using new() or edition a received resource?

**Comment by Maan511** [comment]
Hi @pablorsk 

It is a received resource.

The problem occurs when I:
1. Fetch resources from server that have a to-one relationship, which has not been set. 
2. Call `.save()` on one of the resources. Then `"relationship-name": { "data": { } }` is sent to the server.

I believe it originates from here:
https://github.com/reyesoft/ngx-jsonapi/blob/dd6b0a721cba0f1231152c9528239e48eac6e3c6/src/resource.ts#L87

I will try to build an example, as soon as time allows it.

**Comment by maxi7587** [comment]
I think we can close this issue, since #141 fixed empty relationships structure...
