### ISSUE TITLE
How do i read relationships between two tables

### ISSUE THREAD

**Issue by habatmu-birhanu** [reyesoft/ngx-jsonapi#148]
I can see that server is responding the resources with their relations
but i cant access the relation data through the relationship object

Any help will be appreciated

**Comment by maxi7587** [comment]
Hi! Can you post an example of the resource with its relationships?

**Comment by habatmu-birhanu** [comment]
> Hi! Can you post an example of the resource with its relationships?

Here is what happened to my code .
I have a department and structure table. a department belongs to one structure and structure have many departments. the relationships is one to many. 
In post-man when i asks for department and also i include structure in query parameter I can see that the server is responding with relationships  see below

**Query => http://localhost:3000/departments?include=structure**

Result  => {
    "data": [
        {
            "id": "1",
            "type": "department",
            "attributes": {
                "name": "Mathematics",
                "code": "Mat",
                "category": "",
                "status": true
            },
            "relationships": {
                "structure": {
                    "data": {
                        "id": "1",
                        "type": "structure"
                    }
                }
            }
        },
        {
            "id": "2",
            "type": "department",
            "attributes": {
                "name": "Biology",
                "code": "Bio",
                "category": "",
                "status": true
            },
            "relationships": {
                "structure": {
                    "data": {
                        "id": "1",
                        "type": "structure"
                    }
                }
            }
        }
    ],
    "included": [
        {
            "id": "1",
            "type": "structure",
            "attributes": {
                "name": "Technology",
                "amharic_name": "ቴክኖሎጂ",
                "short_name": "Tech",
                "structure_type": "College",
                "status": false,
                "description": "Description for Structure of Technology",
                "parent_structure_id": null,
                "institution_id": 1
            }
        }
    ],
    "links": {
        "self": "http://localhost:3000/departments.1",
        "last": "http://localhost:3000/departments.2"
    }
}

But when i see it in the console it doesn't build relationship

**Service for  and Model for my department**

import { Department } from './../models/department.model';
import { Injectable } from '@angular/core';
import { Autoregister, Service } from 'ngx-jsonapi';

import { Resource, DocumentCollection } from "ngx-jsonapi";

@Injectable()
@Autoregister()
export class DepartmentsService extends Service<Department> {
  public resource = Department;
  public type = 'department';
  public path = 'departments'
}

**department model**
import { Resource, DocumentCollection } from "ngx-jsonapi";
import { Structure } from "./structure";
export class Department extends Resource{
    public attributes = {
        name: '',
        code: '',
        category: '',
        status: ''
    };
public relationships = {
    structure: new DocumentCollection<Structure>()
};

}

Services and Model for Structures

import { DocumentCollection } from 'ngx-jsonapi';
import { Injectable } from '@angular/core';
import { Autoregister, Service, Resource } from 'ngx-jsonapi';
import { Structure } from '../models/structure';

@Injectable()
@Autoregister()
export class StructureService extends Service<Structure> {

  public resource = Structure;
  public type = 'structure';
  protected path ='structures';

}

Structre Model

import { Department } from './department.model';
import { Resource, DocumentCollection } from 'ngx-jsonapi';
export class Structure extends Resource {
    public attributes = {
        name: '',
        amharic_name: '',
        short_name: '',
        structure_type: '',
        status: 'boolean',
        description: '',
        institution_id: 'number',
        parent_structure_id: ''
    };
  
    public relationships = {
        departments: new DocumentCollection<Department>(),
    };
  
  }




// This where i call for getting department along side with their strcutures
export class DepartmentsComponent implements OnInit {

  public departments: DocumentCollection<Department>;
  constructor(private departmentsService:
    DepartmentsService, private structureService: StructureService) { }

  ngOnInit() {
    this.departmentsService.all({
      page: { number: 1 || 1 },
      include: ['structure']
    }).subscribe(
      departments => {
        this.departments = departments
      },
      error => console.log(error),
    )
  }
}

Here is what i get when i inspect it in console and network xhr tab. In newtork response tab i can see that the server is responding with their relationships but in console the ngx-json api doesn't buld the realtioship  
![conseole](https://user-images.githubusercontent.com/27028157/51299987-4911d500-19f8-11e9-8cb4-ef6b1339a788.png)
![network](https://user-images.githubusercontent.com/27028157/51299988-4911d500-19f8-11e9-928d-fcdc98c4bfce.png)

**Comment by a-radys** [comment]
I had similar issue when getting a single resource. Apparently there is sth wrong with `get` method, because changing `get` to `all` solved the problem.

**Comment by maxi7587** [comment]
Hi @aradys and @habatmu-birhanu  ! Can you send an example of the resources and services so I can try to debug and solve this issue?

**Comment by pablorsk** [comment]
problem solved on 2.1.15
https://github.com/reyesoft/ngx-jsonapi/pull/217/files#diff-b51fd02abd23a9828cff88e6483f42daR364-R369
