### ISSUE TITLE
Relationships builded property is not being updated

### ISSUE THREAD

**Issue by maxi7587** [reyesoft/ngx-jsonapi#152]
Error:
When requesting a resource with included relationships, this relationships are correctly builded, but the .builded property inside them remains false.

Expected:
I expect the .builded property to be set to true when the relationship is complete

**Comment by habatmu-birhanu** [comment]
This

> Error:
> When requesting a resource with included relationships, this relationships are correctly builded, but the .builded property inside them remains false.
> 
> Expected:
> I expect the .builded property to be set to true when the relationship is complete

I also got the same problem. It should be fixed.

**Comment by maxi7587** [comment]
Solved in PR #154, will be merged soon.

**Comment by pablorsk** [comment]
Resolves #154
