### ISSUE TITLE
Promisify

### ISSUE THREAD

**Issue by umbertix** [reyesoft/ngx-jsonapi#17]
It's more a couple questions than an actual bug.

I'm new to angular 5 and I was wondering if with this library there is a way to promisify it, to chain it. Tried few things but feeling a bit confused about it.

Thx for the library anyway. It's looking good.

**Comment by pablorsk** [comment]
> I'm new to angular 5 and I was wondering if with this library there is a way to promisify it, to chain it. Tried few things but feeling a bit confused about it.

Yeap! you can use, for example, save() method and this return a promise. You can use it. For example:

```
let promise = author.save();
promise.then(
  () =>
    console.log('author saved');
  )
)
.catch(
  () =>
    console.log('author not saved. ERROR.');
  )
);

> Thx for the library anyway. It's looking good.

Thanks to you!

(TIP: on the next major version, we plan use observables ;) )

**Comment by umbertix** [comment]
I was trying with the `.all()` mainly. And it's doesn't seem to like this approach because does not recognize the return type `ICollection` to have `.then`. Thx for the reply.

**Comment by pablorsk** [comment]
You can use the future release `1.0.0-rc.0` vía `yarn add ngx-jsonapi@1.0.0-rc.0`

On this new version you can use observers like

```typescript
        authorsService.all(
            // { include: ['books', 'photos'] }
        )
        .subscribe(
            authors => {
                this.authors = authors;
                console.info('success authors controller', authors);
            },
            error => console.error('Could not load authors.')
        );
```

If you like use a simple promise, you can do 

```typescript
        authorsService.all(
            // { include: ['books', 'photos'] }
        )
        .toPromise.then(
            authors => {
                this.authors = authors;
                console.info('success authors controller', authors);
            },
            error => console.error('Could not load authors.')
        );
```
