### ISSUE TITLE
How to enable caching?

### ISSUE THREAD

**Issue by a-radys** [reyesoft/ngx-jsonapi#172]
I tried to do the opposite from this issue: https://github.com/reyesoft/ngx-jsonapi/issues/130 and changed `false` to `true` like this:
```
    NgxJsonapiModule.forRoot({
      url: '/',
      cache_prerequests: true,
      cachestore_support: true
    })
```
but all the http requests are sent every time, like the cache is not working.
Should I set something more?

**Comment by maxi7587** [comment]
Hi aradys, have you set `ttl` in the resources that are not being cached?

**Comment by a-radys** [comment]
Setting `ttl` solved the problem, thanks!
