### ISSUE TITLE
Creating new resource wipes all attributes

### ISSUE THREAD

**Issue by PiotrBrzezianski** [reyesoft/ngx-jsonapi#177]
I wanted to have some defaults in the class that inherits from Resource when I've noticed that calling service.new() wipes the attributes object to an empty one.

```
public reset(): void {
    this.id = '';
    this.attributes = {};
    this.is_new = true;

    for (const key in this.relationships) {
        this.relationships[key] =
            this.relationships[key] instanceof DocumentCollection ? new DocumentCollection() : new DocumentResource();
        }
    }
```

Any reason this has to be like that? If this is intentional can it be made optional?

**Comment by maxi7587** [comment]
You can instantiate the resource class using `new YourResourceClass()`. This should use your default values.

**Comment by PiotrBrzezianski** [comment]
Sure I can reproduce what the Service.new() method would do but that doesn't feel right. It links up the service to the resource and sets the type up. It seems to me that it is perfectly acceptable that reset method is clearing things up but I'm not sure why new() should be calling into reset()...

**Comment by pablorsk** [comment]
You need to use Service.new() for obtain a clean reset and clean Resource. On v2.1.x, version we work on this funciton, now work better! And is fully tested :)

Please, if you detect an error, open a PR o just comment here with an example (actual and spected result)

**Comment by pandabamboo90** [comment]
I had the same issue, however as @maxi7587 suggested, I can init new user with default attributes

```
this.user = this.userApi.new();
this.user.attributes = new User().attributes;
```
