### ISSUE TITLE
Error response on .save() does not produce processable object

### ISSUE THREAD

**Issue by El-scradge** [reyesoft/ngx-jsonapi#181]
Using .save().subscribe( response => {}, error => { error } produces ->  Error: [object Object] instead of the response object from the server like it does from .get() and .all().

**Comment by pablorsk** [comment]
You can use the original object, because is a pontier to same memory location. Library, when you save object, dont create a new one, just replace data on origual data.

For example:
```
author.save().subscribe(response => console.log('all data is from server', author); );
```
