### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by iamchrismiller** [reyesoft/ngx-jsonapi#187]
How come the NPM Releases aren't in sync with reality? 

I am using 2.0.2 and it is telling me to upgrade to 2.0.3 and I have no way to do a diff of the changes? It feels entirely wrong to pull in the latest without knowing what changed.

The active branch is v2.0, no development/master branch.

Is this library no longer maintained? Should the users of this project move onto this library? https://github.com/ghidoz/angular2-jsonapi

**Comment by pablorsk** [comment]
Yeap, we have a problem with NPM versions. Will be work whith @maxi7587 about this subject.
