### ISSUE TITLE
Removing Localforage / Respect Caching Configuration

### ISSUE THREAD

**Issue by iamchrismiller** [reyesoft/ngx-jsonapi#188]
In Safari we see user request for WebSql Allocation.

Seems like the culprit is Localforage even though we have opted out of caching explicitely.

```
    NgxJsonapiModule.forRoot({
      url: '/',
      cache_prerequests: false,
      cachestore_support: false
    }),
```

**Comment by pablorsk** [comment]
This will be fixed on #208
