### ISSUE TITLE
Warning in Spanish (?) "esto no debería pasar. buscar"

### ISSUE THREAD

**Issue by a-radys** [reyesoft/ngx-jsonapi#189]
When I enabled `cachestore_support` like this:
```
    NgxJsonapiModule.forRoot({
      url: '/',
      cache_prerequests: true,
      cachestore_support: true
    }),
```
I started to get this warning:
`ts-angular-json: esto no debería pasar. buscar eEa2ASd2#`
Can you help me get rid of the warning?

**Comment by pablorsk** [comment]
Removed on v2.1.7
