### ISSUE TITLE
Service.get() do not return the resource if TTL is enabled

### ISSUE THREAD

**Issue by ivelichko** [reyesoft/ngx-jsonapi#198]
If TTL is enabled and resource is alive, `.get` call returns a Subject which cannot be properly subscribed.
https://github.com/reyesoft/ngx-jsonapi/blob/v2.0/src/service.ts#L82 - here `.complete()` is called, which completes the returning Subject
And this `.next` call has no effect: https://github.com/reyesoft/ngx-jsonapi/blob/v2.0/src/service.ts#L104

I'd suggest to call `.next` before `.complete` in that case

**Comment by pablorsk** [comment]
Related with #208, maybe your problem will fixed.

**Comment by ivelichko** [comment]
> Related with #208, maybe your problem will fixed.

Thanks, I'll recheck when #208 is merged

**Comment by pablorsk** [comment]
Now, is fully tested :) No same problem again :smile:
