### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by andreaskrauss** [reyesoft/ngx-jsonapi#201]
Hey,

I have an issue on your demo app.
![reyesoft_ngx_jsonapi_demo](https://user-images.githubusercontent.com/15679969/62886275-361b7500-bd3b-11e9-9da5-54132d7822c5.PNG)
As shown in the picture the app seams to have an issue connecting to your background.

One source of the issue might be the wrong url.
When I open the Debugging console of Chrome, thre requests are listed as **Stalled**.
When I call the requested links in a separate tab, I receive the correct JSON:API conform JSON objects.

[Google Developers](https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation) says for that status:

> **Stalled**. The request could be stalled for any of the reasons described in Queueing.

These reasons are:
> - There are higher priority requests.
> - There are already six TCP connections open for this origin, which is the limit. Applies to  HTTP/1.0 and HTTP/1.1 only.
> - The browser is briefly allocating space in the disk cache

Am I having a local issue here? Or does someone has a similar issue?

I tested the issue on:
OS: Windows
Browsers: Chrome v76 and Firefox v68

Thanks in advance for helping.

Best regards

**UPDATE**
I tried to analyse the network communication again. This time Chrome marked the request as *blocked:mixed-content* .  Loading unsafe scripts, did not solve the issue.

**Comment by pablorsk** [comment]
Thanks for your report @andreaskrauss
