### ISSUE TITLE
Header missing

### ISSUE THREAD

**Issue by umbertix** [reyesoft/ngx-jsonapi#22]
So far only tried the get, but the header is missing. So If following the standard I get a http error 406.

I've tried with both with the rc branch with observables and the master one.

**Comment by pablorsk** [comment]
you are rigth, problem solved on PR #24, please use version `0.2.1`

**Comment by umbertix** [comment]
I believe that the headers information is inverted. 
Content type and Accept header should have each other value.

![headers_inverted](https://user-images.githubusercontent.com/708948/34458377-7245a206-edc8-11e7-9fc0-0e24f62978d0.jpg)
