### ISSUE TITLE
Serialize resource object

### ISSUE THREAD

**Issue by ZahraAmiri1996** [reyesoft/ngx-jsonapi#238]
Hello, I want to serialize Resource object and then get string of serialized object and  send it as parameters in URL also like formurlencoded in HTTP request . 
How to serialize it ?

**Comment by pablorsk** [comment]
Hi!

You are broken jsonapi specifcation doing that. But, if you still want to do it, it just does

```
let data_string = resource.toObject().stringify().
```

Then, you send `data_string` to server.
