### ISSUE TITLE
serialize and deserialize

### ISSUE THREAD

**Issue by ehsan5** [reyesoft/ngx-jsonapi#247]
hi,
I want to convert string to jsonapi object and resource,Can you help me?

**Comment by maxi7587** [comment]
Hi @ehsan5 !

I would follow this steps: 

1. Use JSON.parse to convert the string to Object.
2. Your Object (let's call it `new_object`) should  satisfy IDocumentResource or ICacheableDocumentResource interfaces, so you can create a new resource (`new_resource`) of the desired type and use `new_resource.fill(new_object)`.

This way, `new_resource` get's filled with the information from `new_object`.

Please tell me if this worked for you!
