### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Rentier** [reyesoft/ngx-jsonapi#25]
I copy pasted the example in a newly generated angular project. I get the following error in the **AuthorsComponent**

```
[ts]
Type 'Observable<ICollection<Resource>>' is not assignable to type 'ICollection<Resource>'.
  Property '$length' is missing in type 'Observable<ICollection<Resource>>'.
```

This occurs in the line 

`this.authors = authorsService.all(
`

```
"@angular/common": "^5.0.0",
"ngx-jsonapi": "^1.0.0-rc.0",
```

**Comment by pablorsk** [comment]
Hi @Rentier,

for ngx-jsonapi `1.0.0-rc.0` version, plese use this [README info](https://github.com/reyesoft/ngx-jsonapi/tree/v1).
