### ISSUE TITLE
async/await problem - how to handle it

### ISSUE THREAD

**Issue by hanusiakl** [reyesoft/ngx-jsonapi#26]
Hi,

Please, take a look on following code.

DeviceService 

```javascript
@Injectable()
export class DeviceService extends Service {
   async getAllDevices(): Promise<any> {
        console.log('START');
        const d = await this.all().toPromise(); //super.all().toPromise()
        console.log('FINISH');
        return d;
}
```

Component
```javascript
export class DevicesListComponent {
......
   async ngOnInit() {
       const data1 = await this.devicesService.getAllDevices(); //  not working
       console.log('THIS TEXT IS NOT DISPLAYED');
       const data2 = await this.devicesService.all().toPromise(); // without 'proxy' function - not working too
       console.log('THIS TEXT IS NOT DISPLAYED');   
  }
...
}
```

   During reading **data1** or  **data2** there is no error in console. Only **START** is displayed. 
When I open **Network** tab in Chrome dev-tools, I see that request is finished with success and even return correct data.

Do you know how I should handle async/await when I use ngx-jsonapi ?

Kind Regards,
Leszek

**Comment by pablorsk** [comment]
Hi @hanusiakl,

Please, can you check your console tab? Probably you can see some errors. Also, if you can do an example, great.

Also, check if you are using version `^1.0.0`, that version work with observables.

**Comment by hanusiakl** [comment]
Hi, @pablorsk.

It is weird, but console tab is clean, no error there. After 'START' there is no more messages.
I`m using ngx-jsonapi: "^1.0.0-rc.2.

**Comment by pablorsk** [comment]
a `complete()` call was missing. Try again with `1.0.0-rc.4` version.

**Comment by hanusiakl** [comment]
work like a charm. Thanks.
