### ISSUE TITLE
Save method from Resource not working well, at least for new resources.

### ISSUE THREAD

**Issue by hanusiakl** [reyesoft/ngx-jsonapi#27]
Hi,

   After create new resource for e.g: [new()](https://github.com/reyesoft/ngx-jsonapi/blob/master/demo/app/authors/components/author.component.ts#L49), and then save it [save()](https://github.com/reyesoft/ngx-jsonapi/blob/master/demo/app/authors/components/author.component.ts#L56), I received **201** from server, and entity is created. 

Unfortunatelly, I also see error in my code something like this

``` 
TypeError: Cannot read property 'attributes' of undefined
    at Function.Converter._buildResource (ngx-jsonapi.es5.js:1162)
    at Function.Converter.build (ngx-jsonapi.es5.js:1120)
```

   Propably I found the reason. 

Reponse from server looks like 
```javascript
data: {
   ....
   attributes: { },
   id: {}
.....
}
``` 
After response from server, we try to convert result 
[conver_after_response](https://github.com/reyesoft/ngx-jsonapi/blob/master/src/resource.ts#L231).
We are send ```success.data``` into ```Converter.build``` method.
```Converter.build``` method passes ```undefined``` content in this line 
[document_from.data](https://github.com/reyesoft/ngx-jsonapi/blob/master/src/services/converter.ts#L115) and next exception is thrown.
It is undefined because data property was extracted before (```success.data```).

Temporary workaround for this problem is passing ```success``` instead of ```success.data``` to ```Converter.build```.

Thanks,
Leszek

**Comment by pablorsk** [comment]
Your problem was solved on `1.0.0-rc.5` version :man_mechanic:
