### ISSUE TITLE
Accept Header

### ISSUE THREAD

**Issue by umbertix** [reyesoft/ngx-jsonapi#30]
Is there any way to pass extra headers into the http service? I can't see any way, but I don't know if you have a branch with this changes or not.
In my API I do expect the `Accept` header with the `application/vnd.api+json`, as the standard defines. Not fully clued with the standard yet but I believe that is expected in some cases so probably should be there.

Thx for the push that you've been doing last week 👍

**Comment by hanusiakl** [comment]
Hi @umbertix ,

You can use HttpInterceptor. 

For eg: 
```javascript
@Injectable()
export class KeycloakHttpInterceptor implements HttpInterceptor {

  constructor(private keycloakService: KeycloakService) {
  }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const tokenPromise: Promise<string> = this.keycloakService.getToken();
    const tokenObservable: Observable<string> = Observable.fromPromise(tokenPromise);

    return tokenObservable.flatMap(token => {
      const clonedRequst: HttpRequest<any> = req.clone({
        headers: req.headers.set('Authorization', `Bearer ${token}`)
          .set('Content-Type', 'application/vnd.api+json')
          .set('Accept', 'application/vnd.api+json'),
        withCredentials: true,
      });

      return next.handle(clonedRequst);
    })
  }
}
```

**Comment by umbertix** [comment]
Just created a PR with the suggested changes: https://github.com/reyesoft/ngx-jsonapi/pull/31

**Comment by umbertix** [comment]
I'll take a look to that solution, thx. But seems a bit of an overkill when surely is something that people will need as a basic thing when calling APIs

**Comment by pablorsk** [comment]
Thanks @umbertix, #31 accepted. 

The solution by @hanusiakl is great for tokens. We use [auth0/angular-jwt](https://github.com/auth0/angular-jwt) and works fine with **ngx-jsonapi**.
