### ISSUE TITLE
Error when using toPromise

### ISSUE THREAD

**Issue by umbertix** [reyesoft/ngx-jsonapi#34]
On the latest rc if I try to use the observable and the function toPromise the console spits an error.
![untitled](https://user-images.githubusercontent.com/708948/34469362-0e58f97a-ef15-11e7-9fdc-62d0c045d159.png)

**Comment by pablorsk** [comment]
Hi @umbertix,

Can you share the code, please?

**Comment by umbertix** [comment]
`        return this._categoriesService
            .all()
            .toPromise()
            .then((categories) => {
                console.log(categories);
                debugger;
            })
            .catch((error) => {
                console.log(error);
                debugger;
            });`

Where categoryservice is:
`
@Injectable()
export class CategoryService extends Service<Category> {
    public resource = Category;
    public type = 'products/categories';
    public schema: ISchema = {
    };
}`

My current Ischema is empty because I have no relationships currently.
And Category class is:

`import {Resource} from 'ngx-jsonapi';

export class Category extends Resource {
    public attributes: {
        name: string;
        description: string;
    };
}
`

**Comment by umbertix** [comment]
Got it. The problem was being caused by my `type` inside the `CategoryService`. I assume that internally you are matching types.

Seems to be working for me now.
