### ISSUE TITLE
Calling new() on a Service not working

### ISSUE THREAD

**Issue by danpoland** [reyesoft/ngx-jsonapi#36]
When I try to call new() on my Services I get a `Cannot read property 'scheme' of undefined.` error. The error is being thrown in the rest method of the Resource class on the below line.

`Base.forEach(this.getService().schema.relationships, (value, key) => {`

Here is a screenshot of the actual console error.

![capture](https://user-images.githubusercontent.com/6596169/34572044-4b2384e4-f13e-11e7-9253-58528237b969.PNG)

**Comment by pablorsk** [comment]
problem solved on `1.0.0-rc.6` :smile:
