### ISSUE TITLE
Authenticated service

### ISSUE THREAD

**Issue by mrizzellowide** [reyesoft/ngx-jsonapi#37]
Hello,
I'm trying to use ngx-jsonapi with oAuth2 authentication.
Could you tell me if it is feasible? Is there any documentation on it?
Thank you.

**Comment by danpoland** [comment]
Are you just trying to attach the access token to requests? If so, you can use HttpInterceptors in Angular. 

https://angular.io/api/common/http/HttpInterceptor

**Comment by mrizzellowide** [comment]
Yup! Seems to be the solution. I didn't know about Interceptors.
Thank you very much!
