### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by umbertix** [reyesoft/ngx-jsonapi#38]
Performing pretty much any action bring a console error, and breaks.

**Comment by pablorsk** [comment]
@umbertix,

Are talking about [http://ngx-jsonapi.reyesoft.com/](ngx-jsonapi.reyesoft.com/)? I just see Warnings, but not errors. Can you post a screenshot, please?

**Comment by umbertix** [comment]
<img width="701" alt="screen shot 2018-01-06 at 18 38 36" src="https://user-images.githubusercontent.com/708948/34642781-e3fea79c-f310-11e7-9377-d134971f93eb.png">

**Comment by pablorsk** [comment]
Very extrange, I work fine for me... :/

![screenshot479](https://user-images.githubusercontent.com/938894/34698653-09757426-f4b8-11e7-9e15-f62c0483e192.png)

Please, wait some seconds to server (its slow the first time, I need work on it).

**Comment by umbertix** [comment]
Try updating or adding an author.

**Comment by pablorsk** [comment]
DNS of ngx-jsonapi.reyesoft.com and jsonapiplayground.reyesoft.com are fixed! :tada: 

We are on DigitalOcean now :)
