### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by umbertix** [reyesoft/ngx-jsonapi#39]
Hi I've tried to update one of my reults following the example but does not seem to be liking it.

I've tried with this code:
```
this._categoryService.get(categoryId)
                .toPromise()
                .then((category) => {
                    category.attributes.name = this.form.get('name').value;
                    category.attributes.description = this.form.get('description').value;
                    return category.save();
                })
                .then((response) => {
                    console.log('all good');
                })
                .catch((error) => {
                    console.error(error);
                });
```

But i keep recieving the error attached. Also tried with `.subscribe` but I've got a similar result. I've tried checking the demo site but can't it to work.
<img width="1308" alt="screen shot 2018-01-04 at 19 55 48" src="https://user-images.githubusercontent.com/708948/34581738-71cad8b8-f189-11e7-8291-95cdb2b8e2c7.png">

**Comment by pablorsk** [comment]
problem solved on `1.0.0-rc.6` :smile:

**Comment by pablorsk** [comment]
I try with included demo, and work fine. The code

```typescript
this.booksService.get(id)
    .toPromise()
    .then((book) => {
        book.attributes.title = book.attributes.title + 'x';
        console.log(book.toObject().data.relationships);
        console.log(book.relationships);
        return book.save();
    })
    .then((response) => {
        console.log('all good', response);
    })
    .catch((error) => {
        console.error('err :/', error);
    });
```

Work fine for me.

![screenshot482](https://user-images.githubusercontent.com/938894/34700085-cf24781e-f4bf-11e7-91d3-adf503144941.png)


Can you post data returned of server? On my case is:
```json
{
    "data": {
        "type": "books",
        "id": "7",
        "attributes": {
            "title": "Ledner-Stehrx",
            "date_published": "1979-11-10",
            "isbn": null
        },
        "relationships": {
            "author": {
                "data": {
                    "type": "authors",
                    "id": "29"
                }
            },
            "chapters": {
                "data": []
            },
            "photos": {
                "data": [
                    {
                        "type": "photos",
                        "id": "157"
                    }
                ]
            },
            "serie": {
                "data": {
                    "type": "series",
                    "id": "49"
                }
            },
            "stores": {
                "data": [
                    {
                        "type": "stores",
                        "id": "26"
                    }
                ]
            }
        },
        "links": {
            "self": "/v2/books/7"
        }
    }
}
```

**Comment by umbertix** [comment]
I think that I got what is actually going on. My response is a `202`, I believe that this is causing the problem since is not the expected `201`. I'll try update it in the following days, but most likely is my side of the implementation so we can close this issue. The element is sent correctly. :)

**Comment by pablorsk** [comment]
@umbertix the library has no difference betwen 201 and 202. Please check and post for help. Thanks for your collaboration

**Comment by umbertix** [comment]
Ok.. So the actual request is succesfull and the data updates. So is partially correct. But by using this code for example
```
const category = this._categoryService.new();
                    category.attributes.name = this.form.get('name').value;
                  category.attributes.description = this.form.get('description').value;
                    return category.save()
                .then(() => {
                    swal('Congratulations!', 'The category has been added!', 'success');
                })
                .catch((error) => {
                    swal('Oops!', 'Something went wrong!', 'error');
                });
```

I always stomp on the catch, rather than actually resolving the `.then`. And I get an error in console
<img width="445" alt="screen shot 2018-01-09 at 17 29 02" src="https://user-images.githubusercontent.com/708948/34734196-df38df4e-f562-11e7-99d4-44cb1a01419d.png">
<img width="1330" alt="screen shot 2018-01-09 at 17 27 11" src="https://user-images.githubusercontent.com/708948/34734197-df5182ba-f562-11e7-932f-70b2ad1a7bb9.png">

**Comment by pablorsk** [comment]
@umbertix, some ideas...

1. please check are you ussing last version of library.
3. Also, `relationships.ingredients.data` and `relationships.products.data` are not arrays, then I think service marked `hasMany: false` right?

If the problem persists, Can you show me lines where you get the error? I cant follow lines on chuncked code :(. A response on plain text will be better.

**Comment by umbertix** [comment]
1. I'm using `1.0.0-rc.7` which I believe is the latest version.
2. Not sure what you actually mean here.. I attach a screenshot of my service conf. atm.
<img width="444" alt="screen shot 2018-01-10 at 00 13 18" src="https://user-images.githubusercontent.com/708948/34749836-9a99c748-f59b-11e7-9382-225ef08ead44.png">

The lines where I get the error is exactly the one that I pasted.
If u add me on skype umbi369 I can send you the curl/url privately

**Comment by pablorsk** [comment]
@umbertix, on `1.0.0-rc.8` we set with default values when server data id, attributes or relationships are not defined.

Please, if the problem persists, post text of your code and server response.
