### ISSUE TITLE
How to send doimain auth cookies through resource's request?

### ISSUE THREAD

**Issue by emmanueldaher** [reyesoft/ngx-jsonapi#48]
Hello guys,

I'm creating an app that is deployed in my domain, lets say 'enterprise.com.br', and this domain has some cookies for the authetication, my app is in another url in the same domain like 'app.enterprise.com.br'.

All the requests for statics resouces are taking the cookies correctly, but the jsonapi requests doesn't..

Does anyone can help?

**Comment by emmanueldaher** [comment]
well guys,
I've found the solution and, shame on me...

Just use a HttpInterceptor and set withCredentials: true  when requestis for the desired domain.

`import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler } from '@angular/common/http';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

    constructor() { }

    intercept(req: HttpRequest<any>, next: HttpHandler) {

        // Clone the request and replace the original headers with
        // cloned headers, updated with the authorization.
        let authReq = req;

        if (req.url.indexOf('.enterprise.com.br') != -1) {
            authReq = req.clone({
                withCredentials: true
            });
        }

        // send cloned request with header to the next handler.
        return next.handle(authReq);
    }
}`

**Comment by letsbelopez** [comment]
I'm having the same issue. I have an http interceptor that makes every request `withCredentials: true`, but this library is still sending requests `withCredentials: false`

@emmanueldaher do you know what would cause that?

I'm using @Injectable({providedIn: 'root'}) for the services, and I'm providing my `HttpInterceptors` like in the [angular docs](https://angular.io/guide/http#provide-the-interceptor), but I don't think that should matter.

**Comment by emmanueldaher** [comment]
@letsbelopez could you share your code? the module where you are registring the interceptor, and the interceptor...
