### ISSUE TITLE
Success on connection refused

### ISSUE THREAD

**Issue by zeevkatz** [reyesoft/ngx-jsonapi#49]
When connection refused .map() still invoked and .catch() immediately after.

```
    this.rolesService
      .all() <= Connection refused
      .filter(data => !data.$is_loading)
      .map(data => {  <= Map triggered.
        return new roles.LoadSuccessAction(data.$toArray)
      })
      .catch(error => { <= And catch immediately after.
        return Observable.of(new roles.LoadFailedAction(error)) 
      })
```

**Comment by pablorsk** [comment]
Have you been able to reproduce the error in the demo app?

I try to do the same on demoapp, but filter method dont exits on Observable type. :/

**Comment by zeevkatz** [comment]
If you are using rxjs@5.5^ try to use filter method in .pipe()

**Comment by pablorsk** [comment]
Demo app works with angular ^5.1.0, and resolve angular 5.2.10. If you check package.json, [works with rxjs@5.5.5](https://github.com/angular/angular/blob/5.2.10/package.json#L31).

I check on Observable.d.ts of rxjs, and nothing about filter().

Sorry, I don't have much experience on rxjs.
