### ISSUE TITLE
Path property to public scope

### ISSUE THREAD

**Issue by sunel** [reyesoft/ngx-jsonapi#57]
I can see that a custom path can be given 

https://github.com/reyesoft/ngx-jsonapi/blob/5cd065c1ae63e551a447a158b1316c3e8ff5c1bb/src/service.ts#L76-L78

But as path is private property it throws error while extending it in the child class, so it is better to change it to public property

https://github.com/reyesoft/ngx-jsonapi/blob/5cd065c1ae63e551a447a158b1316c3e8ff5c1bb/src/service.ts#L34

**Comment by pablorsk** [comment]
Why you don't extend getPath() function?

If you have a good anwswer, maybe we can convert path property from private to protected.

**Comment by sunel** [comment]
Extending `getPath()` is now the only way, but if we do that `private path: string;` is of no use as it is only used in the `getPath()` function

**Comment by sunel** [comment]
The current implementation also check if the path is set, but its not allowed as it is private variable.

**Comment by pablorsk** [comment]
Hi @sunel, `protected` it's ok for you?
