### ISSUE TITLE
Can't build when using Angular 4.3

### ISSUE THREAD

**Issue by frans-beech-it** [reyesoft/ngx-jsonapi#67]
The readme states that the library is compatible with Angular 4+ but when building the project we run into the next error:

```
ERROR in Error: Metadata version mismatch for module node_modules/ngx-jsonapi/index.d.ts, found version 4, expected 3, resolving symbol AppModule in app/app.module.ts, resolving symbol AppModule in app/app.module.ts, resolving symbol AppModule in app/app.module.ts
```

**Comment by frans-beech-it** [comment]
Upgraded our project top Angular 5.2 and now we can build it correctly.

Maybe just set the minimum dependency to Angular 5? And state Angular 5+ in the readme?

**Comment by pablorsk** [comment]
What do you think about PR @frans-beech-it?
