### ISSUE TITLE
Eager loaded relations aren't correctly populated

### ISSUE THREAD

**Issue by frans-beech-it** [reyesoft/ngx-jsonapi#68]
Maybe we are just missing something. But we run into the issue that relations loaded thought the `?include=` parameter aren't correctly populated when the service beloning to that service isn't registered manually.

If the service belonging to the related object isn't loaded the relation has an `id` but the `content` variable has the value `none`.

You can also see this behavior in the demo:

- If you go directly to http://ngx-jsonapi.reyesoft.com/#/authors/1 you don't see any books.
- If you navigate then to books and go back to this author then you see the books are visible

We added the following workaround to `app.module.ts` of our project:

```
export class AppModule {
    // temp workaround to be sure nested relations are correctly loaded/filled
    constructor(protected usersService: UsersService) {
        usersService.register();
    }
}
```

**Comment by pablorsk** [comment]
apparently, the `autoloader` decorator isn't working... :thinking:

**Comment by pablorsk** [comment]
Hi @frans-beech-it, I added again `@Autoregister` decorator. With decorator, `service.register();` is not required, but still necesary inject service.

Any ideas for a way  to injection of dependency is not necessary?

**Comment by sunel** [comment]
@pablorsk  Same here relations  are not getting loaded properly and has a wired behavior 

This is my service file with relation 

![5](https://user-images.githubusercontent.com/1009777/40996405-48bc6c94-691f-11e8-9100-99376884994c.PNG)

This is the response from the server 

![1](https://user-images.githubusercontent.com/1009777/40996313-27309b0e-691f-11e8-964e-ec7a0af57dee.PNG)

I log the input to the _buildResource 

![2](https://user-images.githubusercontent.com/1009777/40996449-68af4e9a-691f-11e8-96a0-f7e7cdde4d90.PNG)

If you notice the relationship data for skills has only one value but the logged shows two values


Log from  localstorage
![3](https://user-images.githubusercontent.com/1009777/40996608-d999cf90-691f-11e8-87ac-cf58b62d72ed.PNG)

More logs from printing the data

![4](https://user-images.githubusercontent.com/1009777/40996640-f1edb49e-691f-11e8-83e5-707533a1e05d.PNG)

Some times only this shows up

![6](https://user-images.githubusercontent.com/1009777/40996649-f4213600-691f-11e8-87fe-f24c6bc37f37.PNG)

**Comment by sunel** [comment]
And Additional the data is loaded is behaving differently when cache is enabled 

Without cache or first time when loaded

![2](https://user-images.githubusercontent.com/1009777/41051403-ad1d18b4-69d3-11e8-85ec-0171ffe2218f.PNG)

With Cache after first time

![1](https://user-images.githubusercontent.com/1009777/41051431-bd736326-69d3-11e8-9693-f5c2d68f7241.PNG)

**Comment by pablorsk** [comment]
I think original issue by @frans-beech-it  was solved in #71 

@sunel, Your example I don't understand very well.... If you open a new issue with the same example data but add and example uri and method?

**Comment by sunel** [comment]
@pablorsk created #78

**Comment by ouranos** [comment]
Working for me with the workaround @frans-beech-it suggested :clap: .
Waiting for a release including #71 to test `Autoregister()`.

Does it work with multi level association?
eg: `include: ['author', 'photos', 'photos.comments']`

In my case the first relationship (`photos`) has an extra relationship (`comments`) but it's empty:
```json
{
  "content": "none",
  "data": {}
}
```
I'll keep playing as it might come from my code.

Let me know if I should open a new issues or if you have some tips :)

**Comment by ouranos** [comment]
@pablorsk any ideas regarding the above?
I tried to reproduce the case with the demo but it looks like the playground doesn't support requesting resources related to other resources, eg:
```
GET /v2/stores/1?include=books.chapters
```

**Comment by adolf86** [comment]
Hi @ouranos. I'm finding the same problem with nested relationships. Have you managed to resolved that issue?

**Comment by pablorsk** [comment]
@adolf86, [JsonApi playground backend](http://jsonapiplayground.reyesoft.com/) dont support include or sorted refereces with `.`.

Try with version 1.1.2 if your problem is with library.

**Comment by ouranos** [comment]
@pablorsk updated to v1.1.4
`@AutoRegister` now works properly but it doesn't seem to fix the problem for nested relationships ("photo.comments" in my example)

**Comment by jonasgrundtvig** [comment]
@ouranos Did you find a solution or fix for the problem with nested relationships?

**Comment by ouranos** [comment]
@jonasgrundtvig No, we do manual HTTP calls and parsing for the few endpoints that need it.
