### ISSUE TITLE
Include the data loaded is behaving differently when cache is enabled

### ISSUE THREAD

**Issue by sunel** [reyesoft/ngx-jsonapi#78]
Include the data loaded is behaving differently when cache is enabled 

Without cache or first time when loaded

![2](https://user-images.githubusercontent.com/1009777/41051403-ad1d18b4-69d3-11e8-85ec-0171ffe2218f.PNG)

With Cache after first time

![1](https://user-images.githubusercontent.com/1009777/41051431-bd736326-69d3-11e8-9693-f5c2d68f7241.PNG)

**Comment by sunel** [comment]
#74 resolves this issue

**Comment by pablorsk** [comment]
Thanks! Inluded on 1.1.3 version :tada:
