### ISSUE TITLE
Does not work properly with Angular 6

### ISSUE THREAD

**Issue by OpticNectar** [reyesoft/ngx-jsonapi#81]
When you try to use this plugin with Angular 6 you get the error:

`Cannot find module 'rxjs-compat/Observable'`

Adding this works for now, but Angular has changed how it uses Observables so this should be changed for the future.

**Comment by maxi7587** [comment]
Hi OpticNectar. Yes, we're aware, but haven't updated yet to mantain compatibility with the previous versions of Angular and rxjs. The import statements of rxjs will be updated in a future release. Thanks!
