### ISSUE TITLE
Proper way to sort data

### ISSUE THREAD

**Issue by OpticNectar** [reyesoft/ngx-jsonapi#84]
I have paginated data coming in from the server and I need to be able to sort the data. I have the sorts working properly on the server side, but obviously this package sorts by Id automatically so it ignores any sorting. Is there a way you recommend or know of that will all the data to be sorted or is this just a huge flaw in this package?

**Comment by MikaStark** [comment]
Up

**Comment by OpticNectar** [comment]
I'd be willing to throw some money towards this fix if someone could add it into the main package or make a fork that sorts based on the server or has a way to sort.
